### ISSUE TITLE
Support for SWupdate only regarding the bootloader info status

### ISSUE THREAD

**Issue by lchagnoleau** [madisongh/tegra-test-distro#10]
First of all, thank you for your amazing work on the Tegra layers.

I'm trying to implement ```SWupdate``` **whiteout** ```RAUC``` or ```Mender``` for the Xavier AGX Devkit using your tegra-test-distro example.
I'm able to correctly flash new partitions using A/B system but there is 2 things that I do not understand how to deal with it:

1. Before using SWupdate for the first time after the flash with tegraflash, I have to initialize by myself  the tegra-bootinfo using:
```bash
tegra-bootinfo --initialize
```
Therefore, I obtain the message ```Could not locate device info``` during SWupdate process.

2. After device well rebooted on the new fresh partitions, there is no process to tell at the system that the partition is well bootable. So I have to write : 
```bash
tegra-boot-control -m
```
e.g:
```bash
root@jetson-agx-xavier-devkit:~# tegra-boot-control -s    
Redundancy: enabled (full)
Current slot: 1
Slot 0: priority: 14, suffix: _a, retry_count: 7, successful: YES
Slot 1: priority: 15, suffix: _b, retry_count: 6, successful: NO
root@jetson-agx-xavier-devkit:~# tegra-boot-control -m
Slot 1 marked successful.
root@jetson-agx-xavier-devkit:~# tegra-boot-control -s
Redundancy: enabled (full)
Current slot: 1
Slot 0: priority: 14, suffix: _a, retry_count: 7, successful: YES
Slot 1: priority: 15, suffix: _b, retry_count: 7, successful: YES
root@jetson-agx-xavier-devkit:~#
```

I'm pretty sure I'm forget something in my layer but I don't what...

Does someone have an idea about this ?
Thank you guys !

**Comment by madisongh** [comment]
The `tegra-boot-tools` recipe generates a couple of packages you should include to take care of these steps for you. For the builds here in my test distro, `tegra-boot-tools-earlyboot` is included in the initrd/initramfs image; that's the one that does the initialization of the boot variables area and also performs the boot count check. `tegra-boot-tools-lateboot` gets included in the main image and takes care of marking the boot successful once systemd finishes bring everything up.

**Comment by lchagnoleau** [comment]
Okay, thanks to your answer, I added in my layer theses package:
```bitbake
    initrd-setup \
    initrd-noncrypt-setup \
    tegra-minimal-init \
    tegra-boot-tools-earlyboot \
```
It seems to work so thanks a lot !
