### ISSUE TITLE
libnvidia-container-tools fails for MACHINE ?= "jetson-xavier-nx-devkit"

### ISSUE THREAD

**Issue by outbackdingo** [madisongh/tegra-test-distro#2]
ERROR: libnvidia-container-tools-0.9.0-r1 do_compile: oe_runmake failed
ERROR: libnvidia-container-tools-0.9.0-r1 do_compile: Execution of '/var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301' failed with exit code 1:
which: invalid option -- 'm'
which: invalid option -- 'r'
which: invalid option -- 'c'
which: invalid option -- 'h'
which: invalid option -- '='
which: invalid option -- 'r'
which: invalid option -- 'm'
/var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/git/mk/common.mk:36: *** Invalid compiler.  Stop.
WARNING: /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301:188 exit 1 from 'exit 1'
WARNING: Backtrace (BB generated script): 
	#1: bbfatal_log, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 188
	#2: die, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 172
	#3: oe_runmake, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 158
	#4: base_do_compile, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 150
	#5: do_compile, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 144
	#6: main, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 192

Backtrace (metadata-relative locations):
	#1: bbfatal_log, /var/home/dingo/tegra-test-distro/layers/meta/classes/logging.bbclass, line 72
	#2: die, /var/home/dingo/tegra-test-distro/layers/meta/classes/base.bbclass, line 56
	#3: oe_runmake, /var/home/dingo/tegra-test-distro/layers/meta/classes/base.bbclass, line 65
	#4: base_do_compile, /var/home/dingo/tegra-test-distro/layers/meta/classes/base.bbclass, line 327
	#5: do_compile, autogenerated, line 2
ERROR: Logfile of failure stored in: /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/log.do_compile.2028301
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 16 WITH_LIBELF=yes JETSON=TRUE WITH_SECCOMP=no
| which: invalid option -- 'm'
| which: invalid option -- 'r'
| which: invalid option -- 'c'
| which: invalid option -- 'h'
| which: invalid option -- '='
| which: invalid option -- 'r'
| which: invalid option -- 'm'
| /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/git/mk/common.mk:36: *** Invalid compiler.  Stop.
| ERROR: oe_runmake failed
| WARNING: /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301:188 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 188
| 	#2: die, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 172
| 	#3: oe_runmake, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 158
| 	#4: base_do_compile, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 150
| 	#5: do_compile, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 144
| 	#6: main, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 192
| ERROR: Execution of '/var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301' failed with exit code 1:
| which: invalid option -- 'm'
| which: invalid option -- 'r'
| which: invalid option -- 'c'
| which: invalid option -- 'h'
| which: invalid option -- '='
| which: invalid option -- 'r'
| which: invalid option -- 'm'
| /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/git/mk/common.mk:36: *** Invalid compiler.  Stop.
| WARNING: /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301:188 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 188
| 	#2: die, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 172
| 	#3: oe_runmake, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 158
| 	#4: base_do_compile, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 150
| 	#5: do_compile, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 144
| 	#6: main, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a-oe4t-linux/libnvidia-container-tools/0.9.0-r1/temp/run.do_compile.2028301, line 192
| 
| Backtrace (metadata-relative locations):
| 	#1: bbfatal_log, /var/home/dingo/tegra-test-distro/layers/meta/classes/logging.bbclass, line 72
| 	#2: die, /var/home/dingo/tegra-test-distro/layers/meta/classes/base.bbclass, line 56
| 	#3: oe_runmake, /var/home/dingo/tegra-test-distro/layers/meta/classes/base.bbclass, line 65
| 	#4: base_do_compile, /var/home/dingo/tegra-test-distro/layers/meta/classes/base.bbclass, line 327
| 	#5: do_compile, autogenerated, line 2
ERROR: Task (/var/home/dingo/tegra-test-distro/layers/meta-tegra/external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6481 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /var/home/dingo/tegra-test-distro/layers/meta-tegra/external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb:do_compile

**Comment by madisongh** [comment]
What OS are you using for your builds, and what is your default shell?  The `mk/common.mk` file for libnvidia-container-tools has:
```
COMPILER := $(realpath $(shell which $(CC)))
```
CC for cross-builds includes not only the compilation command but also some flags, and it looks like in your case the `which` command is trying to interpret those flags.

I can fix the recipe to work around this, but I'm just curious about why this hasn't shown up before.

**Comment by madisongh** [comment]
I've opened [this issue](https://github.com/OE4T/meta-tegra/issues/429) to get this cleaned up.  Will close this one.
