### ISSUE TITLE
tegra-mmapi-samples also appears to fail under jetson-xavier-nx-devkit

### ISSUE THREAD

**Issue by outbackdingo** [madisongh/tegra-test-distro#3]
| make[1]: Leaving directory '/var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/tegra-mmapi/usr/src/jetson_multimedia_api/samples/07_video_convert'
| Make in samples/08_video_dec_drm
| make[1]: Entering directory '/var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/tegra-mmapi/usr/src/jetson_multimedia_api/samples/08_video_dec_drm'
| /usr/bin/python /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/tegra-mmapi/usr/src/jetson_multimedia_api/tools/GetPixel.py -i /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/tegra-mmapi/usr/src/jetson_multimedia_api/data/Picture/nvidia-logo.jpg -o image_rgba.cpp
|   File "/var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/tegra-mmapi/usr/src/jetson_multimedia_api/tools/GetPixel.py", line 44
|     print "WARN: don't error out if PIL is not installed, instead to create a color pattern."
|           ^
| SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARN: don't error out if PIL is not installed, instead to create a color pattern.")?
| make[1]: *** [Makefile:55: image_rgba.cpp] Error 1
| make[1]: Leaving directory '/var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/tegra-mmapi/usr/src/jetson_multimedia_api/samples/08_video_dec_drm'
| make: *** [Makefile:57: all] Error 1
| WARNING: /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/temp/run.do_compile.3080739:185 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/temp/run.do_compile.3080739, line 185
| 	#2: die, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/temp/run.do_compile.3080739, line 175
| 	#3: oe_runmake, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/temp/run.do_compile.3080739, line 164
| 	#4: do_compile, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/temp/run.do_compile.3080739, line 159
| 	#5: main, /var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/temp/run.do_compile.3080739, line 198
| 
| Backtrace (metadata-relative locations):
| 	#1: bbfatal_log, /var/home/dingo/tegra-test-distro/layers/meta/classes/logging.bbclass, line 72
| 	#2: die, /var/home/dingo/tegra-test-distro/layers/meta/classes/base.bbclass, line 56
| 	#3: oe_runmake, /var/home/dingo/tegra-test-distro/layers/meta/classes/base.bbclass, line 65
| 	#4: do_compile, /var/home/dingo/tegra-test-distro/layers/meta-tegra-support/recipes-multimedia/argus/tegra-mmapi-samples_32.4.3.bb, line 50
ERROR: Task (/var/home/dingo/tegra-test-distro/layers/meta-tegra-support/recipes-multimedia/argus/tegra-mmapi-samples_32.4.3.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 8639 tasks of which 6480 didn't need to be rerun and 2 failed.

Summary: 2 tasks failed:
  /var/home/dingo/tegra-test-distro/layers/meta-tegra/external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools_0.9.0.bb:do_compile
  /var/home/dingo/tegra-test-distro/layers/meta-tegra-support/recipes-multimedia/argus/tegra-mmapi-samples_32.4.3.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There were 4 ERROR messages shown, returning a non-zero exit code.

**Comment by madisongh** [comment]
```
| File "/var/home/dingo/tegra-test-distro/build/tmp/work/armv8a_tegra194-oe4t-linux/tegra-mmapi-samples/32.4.3-r0/tegra-mmapi/usr/src/jetson_multimedia_api/tools/GetPixel.py", line 44
| print "WARN: don't error out if PIL is not installed, instead to create a color pattern."
| ^
| SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARN: don't error out if PIL is not installed, instead to create a color pattern.")?
```
Looks like there's a python 2 script being run there.  I'll take a look.

**Comment by madisongh** [comment]
I've merged a fix for this into master.

**Comment by outbackdingo** [comment]
working now, thanks bitbake demo-image-full completes now
