### ISSUE TITLE
Cleanup use of ${TEGRA_SIGNING_EXTRA_DEPS}

### ISSUE THREAD

**Issue by Lexmark-chad** [madisongh/tegra-test-distro#9]
Not urgent.  Just capturing some things we saw when integrating with digsigserver as our signing server.  I have a PR I'm working on, but there are some bitbake / yocto things I need to get clarification on first before submitting.  Things I saw:

- Would be nice if u-boot-bup-payload.bbappend and kernel-bup-payload.bbappend can just `inherit tegrasign`.
- Is this allowed syntax?  `tegraflash_custom_sign[depends] += "gzip-native:do_populate_sysroot"` You can create a dependency between a function and a task?  Furthermore, the function name can be 'wildcarded'?  I.e., `tegraflash_custom_sign` vs `tegraflash_custom_sign_pkg_secureboot` and `tegraflash_custom_sign_bup_secureboot`.
- Dependency created on `gzip-native`, but `tar` is used instead.  Should be `tar-native`?  I'm actually stuck here, because I'm not getting `tar-native` installed into the recipe's native sysroot.

I think because tegrasign's functions are using utilities (`tar` and `curl`) which are very likely to be installed on the host system it happens to work.  I'm not sure the dependency management is occurring as intended.

**Comment by Lexmark-chad** [comment]
This is my approach thus far..

In `tegrasign.bbclass`:

```
TEGRA_SIGNING_EXTRA_DEPS = ""
TEGRA_SIGNING_EXTRA_DEPS_secureboot = "${DIGSIG_DEPS} tar-native:do_populate_sysroot"
```

Then at the bottom of the class create the dependency:

`do_deploy[depends] += "${TEGRA_SIGNING_EXTRA_DEPS}`

In each of `u-boot-bup-payload.bbappend` and `kernel-bup-payload.bbappend` simply:

`inherit tegrasign`

**Comment by madisongh** [comment]
I agree that a bit of cleanup would make things easier.  I think the right answer here, though, is to add
```
TEGRA_SIGNING_EXTRA_DEPS ??= ""
do_deploy[depends] += "${TEGRA_SIGNING_EXTRA_DEPS}"
```
to the `u-boot-bup-payload.bb` recipe in meta-tegra.

**Comment by madisongh** [comment]
I've made the above-mentioned change in meta-tegra master, and dropped the extras from the bbappend in master here.  Looks like it's doing the right thing.

I suppose the next step would be to add support in meta-tegra for a variable like TEGRA_SIGNING_CLASS and adding `inherit ${TEGRA_SIGNING_CLASS}` in the right locations there, so you can just set that variable in your distro configuration and not have to have bbappends at all...

**Comment by Lexmark-chad** [comment]
Don't you need to do the same thing  for `kernel_bup_payload.bb` in `meta-tegra`?

I.e., `do_deploy[depends] += "${TEGRA_SIGNING_EXTRA_DEPS}"`

And, then can `tegrasign.bbclass` be further cleaned up?

Omit `tegraflash_custom_sign[depends] += "gzip-native:do_populate_sysroot"`

**Comment by madisongh** [comment]
> Don't you need to do the same thing for kernel_bup_payload.bb in meta-tegra?

I thought it was covered elsewhere, and interestingly enough worked OK in my tests, but you're right, it should be added there, too.

> Omit tegraflash_custom_sign[depends] += "gzip-native:do_populate_sysroot"

I expect so.

**Comment by madisongh** [comment]
OK, I've updated the `kernel-bup-payload` recipe and have ported that and the `u-boot-bup-payload` change to all the current branches in meta-tegra.  I've also dropped the extra dependency setting in `tegrasign.bbclass`.  Thanks!

**Comment by Lexmark-chad** [comment]
Thanks @madisongh!  I think it all looks solid now.
